// Auto-generated REST routes from proto `google.api.http` annotations.
//
// **Do not edit** — regenerated by `build.rs` when proto files change.
//
// Each handler transcodes HTTP/JSON <-> proto and calls the Tonic service trait,
// sharing auth, validation, and business logic with gRPC handlers.

use std::sync::Arc;

use axum::extract::{Path, State};
use axum::http::{HeaderMap, StatusCode};
use axum::Router;

// =============================================================================
// ProviderService REST routes
// =============================================================================

/// Build Axum REST routes for `ProviderService`.
///
/// Generated from `google.api.http` annotations in `test.proto`.
pub fn provider_service_rest_router<S>(service: Arc<S>) -> Router
where
    S: crate::test::provider_service_server::ProviderService + Send + Sync + 'static,
{
    Router::new()
        .route("/v1/providers/{provider}", axum::routing::delete(rest_provider_service_unlink::<S>))
        .with_state(service)
}

#[allow(clippy::too_many_arguments, clippy::needless_pass_by_value)]
/// `Unlink` — JSON endpoint.
///
/// `DELETE /v1/providers/{provider}`
async fn rest_provider_service_unlink<S>(
    State(service): State<Arc<S>>,
    headers: HeaderMap,
    Path(provider): Path<String>,
) -> Result<StatusCode, tonic_rest::RestError>
where
    S: crate::test::provider_service_server::ProviderService + Send + Sync + 'static,
{
    let mut body = crate::test::UnlinkRequest::default();
    body.provider = match crate::test::Provider::from_str_name(&provider.to_ascii_uppercase()) {
        Some(v) => v as i32,
        None => provider.parse::<i32>().map_err(|_| tonic_rest::RestError::new(tonic::Status::invalid_argument(
            "invalid enum value for 'provider'",
        )))?,
    };
    let req = tonic_rest::build_tonic_request::<_, ()>(body, &headers, None);
    service.unlink(req).await.map_err(tonic_rest::RestError::from)?;
    Ok(StatusCode::NO_CONTENT)
}


// =============================================================================
// Public REST paths (bypass auth middleware)
// =============================================================================

/// REST paths that are marked as public (no authentication required).
///
/// Auto-generated from `google.api.http` annotations on public RPC methods.
/// Used by middleware to identify unauthenticated endpoints.
pub const PUBLIC_REST_PATHS: &[&str] = &[
];

// =============================================================================
// Combined REST router
// =============================================================================

/// Build a combined Axum router with REST routes for all proto services.
///
/// Each service is generic — pass your concrete implementations as `Arc<T>`.
pub fn all_rest_routes<S0>(
    provider_service: Arc<S0>,
) -> Router
where
    S0: crate::test::provider_service_server::ProviderService + Send + Sync + 'static,
{
    Router::new()
        .merge(provider_service_rest_router(provider_service))
}
